nombre: Implementar
en: 
  empujar: 
    ramas: 
      - maestro
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions / checkout @ v2 
      - uses: akhileshns/heroku-deploy@v3.0.0 
        con: 
          heroku_api_key: $ {{secrets.HEROKU_API_KEY}} 
          heroku_app_name: "your_app_name" 
          heroku_email: "su dirección de correo electrónico asociada con Heroku" 
          usedocker: true
          
